Goussanjarga/Controllers/VideoController.cs
using Goussanjarga.Models;
using Goussanjarga.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Goussanjarga.Controllers
{
    [AllowAnonymous]
    public class VideoController : Controller
    {
        public VideoController(ICosmosDbService cosmosDb, ILogger<VideoController> logger)
        {
            this.cosmosDb = cosmosDb;
            _logger = logger;
        }

        private readonly ILogger<VideoController> _logger;
        private readonly ICosmosDbService cosmosDb;
        private Container Container => cosmosDb.GetContainer(Config.CosmosVideos);

        public async Task<IActionResult> Index()
        {
            IEnumerable<Videos> videos = await cosmosDb.GetVideos(Container);

            foreach (var video in videos)
            {
                video.FileName = video.FileName.Trim();
                if (video.FileName.Length % 4 == 0 && Regex.IsMatch(video.FileName, @"^[a-zA-Z0-9\+/]*={0,3}$", RegexOptions.None))
                {
                    var bytes = Convert.FromBase64String(video.FileName);
                    video.FileName = Encoding.UTF8.GetString(bytes);
                }
            }
            return View(videos);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Upload()
        {
            return RedirectToAction("Index", "Upload");
        }

        public IActionResult Edit()
        {
            return RedirectToAction("Index", "Upload");
        }

        public async Task<RedirectToActionResult> Delete(string Id)
        {
            try
            {
                await Container.DeleteItemAsync<Videos>(Id, new PartitionKey(Id));
            }
            catch (CosmosException ex)
            {
                _logger.LogError($"Cosmos Exception CODE: {ex.StatusCode} Message: {ex.Message}");
            }
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Goussanjarga/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Goussanjarga</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="//amp.azure.net/libs/amp/latest/skins/amp-default/azuremediaplayer.min.css" rel="stylesheet">
    <script src="//amp.azure.net/libs/amp/latest/azuremediaplayer.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goussanjarga</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">List of Videos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Upload" asp-action="Index">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Goussanjarga - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>